spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hobbytat?createDatabaseIfNotExist=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        #default_batch_fetch_size: 100
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  org.hibernate.SQL: debug
  #org.hibernate.type: trace
  org.hibernate.orm.jdbc.bind:

cloud:
  aws:
    s3:
      bucket: hobbytat
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}

